const User = require('./User');
const Workout = require('./Workout');
const Strava = require('./Strava');
const Program = require('./SelectedProgram');
const FinishedWorkout = require('./FinishedWorkouts');
const WeeklyGoal = require('./WeeklyGoals');
const Session = require('./Session');
const GoalReps = require('./GoalReps');
module.exports = { User, Workout, Strava, Program, FinishedWorkout, WeeklyGoal, Session, GoalReps };